### ISSUE TITLE
pnpm build fails

### ISSUE THREAD

**Issue by shortthefomo** [tequdev/jshooks-template#1]
<img width="1312" alt="Screenshot 2024-09-05 at 11 14 51" src="https://github.com/user-attachments/assets/118fe760-34f1-4a79-b367-6965a31e24b6">

unsure why its not picking up the contracts/index.ts file that's been generated.

**Comment by tequdev** [comment]
@shortthefomo 
Did you run the `pnpm i` command?

**Comment by shortthefomo** [comment]
dope figured out out... 

never ran `npm install`


should add that to the README, I was blindly following along.

**Comment by tequdev** [comment]
Added🤙
